version: '3'

volumes:
  mysql_data:
  artifacts:

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: jobserv
      MYSQL_USER: jobserv
      MYSQL_PASSWORD: jobservpass
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    image: jobserv
    environment:
      SQLALCHEMY_DATABASE_URI_FMT: "mysql+pymysql://{db_user}:{db_pass}@db/jobserv"
      DB_USER: jobserv
      DB_PASS: jobservpass
      FLASK_DEBUG: 1
      FLASK_AUTO_MIGRATE: /data/ci_jobs/.flask-db-migrate.lock
      STORAGE_BACKEND: jobserv.storage.local_storage
      INTERNAL_API_KEY: ThisIsNotSecure
      # see https://cryptography.io/en/latest/fernet/ for generation steps
      SECRETS_FERNET_KEY: SYQI51hPWmH_YLRtAjj6FjKxxytmWtSMeX0WaRBLtc4=
    volumes:
      - artifacts:/data
    command: "/srv/jobserv/wait-for db:3306 -- /srv/jobserv/docker_run.sh"
    depends_on:
      - db

  lci-web:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  worker-monitor:
    image: jobserv
    # We are technically dependent on mysql. However, we are dependent on the
    # jobserv to actually do db migrations. Therefore, we wait on the jobserv
    # instead of mysql.
    command: "/srv/jobserv/wait-for -t 30 api:8000 -- flask monitor-workers"
    tmpfs:
      - /data/workers
    environment:
      SQLALCHEMY_DATABASE_URI_FMT: "mysql+pymysql://{db_user}:{db_pass}@db/jobserv"
      DB_USER: jobserv
      DB_PASS: jobservpass
    depends_on:
      - lci-web

  git-poller:
    image: jobserv
    command: "/srv/jobserv/wait-for lci-web:80 -- flask run-git-poller"
    environment:
      INTERNAL_API_KEY: ThisIsNotSecure
      STORAGE_BACKEND: jobserv.storage.local_storage
    depends_on:
      - lci-web
    volumes:
      - artifacts:/data

  lava-reaper:
    image: jobserv
    command: "/srv/jobserv/wait-for lci-web:80 -- flask run-lava-reaper"
    environment:
      INTERNAL_API_KEY: ThisIsNotSecure
    depends_on:
      - lci-web
