"""empty message

Revision ID: a3144d629b0e
Revises: ce4c4064d14c
Create Date: 2025-06-13 14:15:33.866432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3144d629b0e'
down_revision = 'ce4c4064d14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('running_acked', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('running_acked')

    # ### end Alembic commands ###
