"""empty message

Revision ID: ce4c4064d14c
Revises: bfe4b68df66e
Create Date: 2025-04-11 14:22:34.209889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4c4064d14c'
down_revision = 'bfe4b68df66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_name', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_column('worker_name')

    # ### end Alembic commands ###
