timeout: 5
triggers:
  - name: git
    type: git_poller
    runs:
      - name: docker-run-option
        container: alpine
        host-tag: amd643
        # The docker run command will include "--user nobody"
        container-user: nobody
        script: compile

scripts:
  compile: |
    #!/bin/sh -ex
    echo "hello as nobody"
